In [2]:
import pandas as pd

## DF

In [3]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['A','B','C'])

# custom index 
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['A','B','C'],index=['x','y','z'])

In [4]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [5]:
df.index.to_list()

['x', 'y', 'z']

In [6]:
df.index.to_list()

['x', 'y', 'z']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [8]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [9]:
df.nunique()

df['A'].nunique()

3

## Load df

In [23]:
coffee_df = pd.read_csv('coffee.csv')

In [11]:
results_df = pd.read_parquet('results.parquet')

In [12]:
olympics_df = pd.read_excel('olympics-data.xlsx',sheet_name='results')

In [13]:
bios_df = pd.read_csv('bios.csv')

## Accessing data with pandas

In [20]:
# loc and iloc

# coffee_df.loc[rows,columns]
coffee_df.loc[0]  #first record in the df
coffee_df.loc[[0,1,5]]

# slicing rows and columns
coffee_df.loc[5:8 , ['Day','Units Sold']]

coffee_df.loc[:, ['Day','Units Sold']]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [ ]:

# similar to loc but use index type. 
coffee_df.iloc[:,[0,2]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [ ]:
# assignment by filtering
coffee_df.loc[1,'Units Sold'] = 10

In [ ]:
# . -> if its a single word or else use []
coffee_df.Day 
coffee_df['Units Sold']

0     25
1     15
2     30
3     20
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

In [28]:
# sort
coffee_df.sort_values('Units Sold', ascending = False)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [32]:
# manual iteration

for index , row in coffee_df.iterrows():
    print(index)
    # print(row)
    # print(row['Units Sold'])

0
1
2
3
4
5
6
7
8
9
10
11
12
13

In [43]:
bios_df.loc[(bios_df['height_cm']>215) & (bios_df['born_country'] == 'USA'), 'name']

# is same as 
bios_df[(bios_df['height_cm']>215) & (bios_df['born_country'] == 'USA')][['name','height_cm','born_country']]

                    name  height_cm born_country
5781      Tommy Burleson      223.0          USA
6722    Shaquille O'Neal      216.0          USA
6937      David Robinson      216.0          USA
123850    Tyson Chandler      216.0          USA

In [46]:
bios_df[bios_df['name'].str.contains('Suman',case = False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
44062,44401,Angsuman Chotisathein,1949-07-21,NaN,NaN,NaN,Thailand,159.0,51.0,NaN
74539,75111,Mariana Suman,1951-07-29,Roman,Neamț,ROU,Romania,164.0,54.0,NaN
89200,89912,Adama Osumanu,1980-12-24,Accra,Greater Accra,GHA,Ghana,190.0,71.0,NaN
100345,101195,Christoph Sumann,1976-01-19,Judenburg,Steiermark,AUT,Austria,182.0,80.0,NaN
101881,102811,Sumangala Sharma,1986-12-30,NaN,NaN,NaN,India,165.0,53.0,NaN
137047,140283,Stribor Suman,2002-03-05,NaN,NaN,NaN,Croatia,NaN,NaN,NaN

In [51]:
# find athletes born in cities that start with a vowel

bios_df[bios_df['born_city'].str.contains(r'A$|E$|I$|O$|U$',na = False)
        ]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
13001,13072,Roberta Bonanomi,1966-10-15,Sotto il Monte Giovanni XXIII,Bergamo,ITA,Italy,201.0,92.0,NaN
62381,62844,Maung Maung Lwin,1919-10-08,Daik-U,Bago,MYA,Myanmar,179.0,95.0,1989-03-28

In [52]:

bios_df[bios_df['born_country'].isin(['USA','GBR','FRA'])
        ]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145467,149194,Elisa Nakab,1998-05-08,Briançon,Hautes-Alpes,FRA,Italy,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

In [57]:
bios_df.query('born_country == "USA"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

## adding and removing columns

In [71]:
coffee_df =coffee_df.copy() 
coffee_df['price'] = 4.99

In [72]:
import numpy as np
coffee_df['new_price'] = np.where(coffee_df['Coffee Type'] == 'Espresso', 3.99,5.99)

In [73]:
coffee_df

          Day Coffee Type  Units Sold  new_price  price
0      Monday    Espresso          25       3.99   4.99
1      Monday       Latte          15       5.99   4.99
2     Tuesday    Espresso          30       3.99   4.99
3     Tuesday       Latte          20       5.99   4.99
4   Wednesday    Espresso          35       3.99   4.99
5   Wednesday       Latte          25       5.99   4.99
6    Thursday    Espresso          40       3.99   4.99
7    Thursday       Latte          30       5.99   4.99
8      Friday    Espresso          45       3.99   4.99
9      Friday       Latte          35       5.99   4.99
10   Saturday    Espresso          45       3.99   4.99
11   Saturday       Latte          35       5.99   4.99
12     Sunday    Espresso          45       3.99   4.99
13     Sunday       Latte          35       5.99   4.99

In [74]:
coffee_df.drop(columns= 'price')

# we didnt modify

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [ ]:
coffee_df.drop(columns='price',inplace=True)
# or
coffee_df = coffee_df.drop(columns='price')

In [77]:
coffee_df['revenue'] = coffee_df['Units Sold'] * coffee_df['new_price']

In [81]:
coffee_df.rename(columns={'new_price':'price'} ,inplace=True)

In [84]:
bios_new = bios_df.copy()

In [85]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]

In [87]:
bios_new.query('first_name == "suman"')

Empty DataFrame
Columns: [athlete_id, name, born_date, born_city, born_region, born_country, NOC, height_cm, weight_kg, died_date, first_name]
Index: []

In [88]:
# handling dates

bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])

In [90]:
bios_new = bios_new.drop(columns='born_date')

In [91]:
bios_new

,athlete_id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime
0,1,Jean-François Blanchy,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12
1,2,Arnaud Boetsch,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01
2,3,Jean Borotra,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13
3,4,Jacques Brugnon,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11
4,5,Albert Canet,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30
145496,149223,Valeriya Merkusheva,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20
145497,149224,Yuliya Smirnova,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08
145498,149225,André Foussard,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19
145499,149814,Bill Phillips,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15

In [94]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year

In [95]:
bios_new

,athlete_id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year
0,1,Jean-François Blanchy,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30,2002.0
145496,149223,Valeriya Merkusheva,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20,1999.0
145497,149224,Yuliya Smirnova,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08,1998.0
145498,149225,André Foussard,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19,1899.0
145499,149814,Bill Phillips,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15,1913.0