In [12]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from urllib.parse import quote_plus

In [13]:
USER = "sa"
PASSWORD = quote_plus("Suman@2026!SQL")
SERVER = "localhost"
DB = "marketingdb"

DRIVER_PATH = "/opt/homebrew/lib/libmsodbcsql.18.dylib"

connection_string = (
    f"mssql+pyodbc://{USER}:{PASSWORD}@{SERVER}/{DB}"
    f"?driver={quote_plus(DRIVER_PATH)}"
    "&Encrypt=no"
)

engine = create_engine(connection_string)

In [14]:
master_df = pd.read_csv("Customer_Master.csv")
update_df = pd.read_csv("Customer_Updates.csv")

In [15]:
# run ronce 
master_df.to_sql(
    name="customer_master",
    con=engine,
    if_exists="replace",
    index=False
)

update_df.to_sql(
    name="customer_update_stage",
    con=engine,
    if_exists="replace",
    index=False
)

15

In [16]:
master_df.head()

,CustomerID,FirstName,LastName,Email,Phone,Address,CurrentFlag,Version,LoyaltyTier,PrevLoyaltyTier,SubscriptionStart,SubscriptionEnd
0,101,John,Doe,john.doe@mail.com,1234567890,123 Main St,1,1,Silver,NaN,2020-01-01,NaN
1,102,Jane,Smith,jane.smith@mail.com,9876543210,456 Oak St,1,1,Gold,NaN,2019-06-15,NaN
2,103,Alice,Johnson,alice.j@mail.com,5551234567,321 Maple St,1,1,Silver,NaN,2021-03-10,NaN
3,104,Bob,Brown,bob.b@mail.com,4449876543,654 Pine St,1,1,Bronze,NaN,2018-11-25,NaN
4,105,Carol,White,carol.w@mail.com,3335558888,987 Cedar St,1,1,Silver,NaN,2022-07-01,NaN

In [17]:
update_df.head()

,CustomerID,FirstName,LastName,Email,Phone,Address,LoyaltyTier,SubscriptionStart,SubscriptionEnd
0,101,John,Doe,john.doe@newmail.com,1234567890,789 Pine St,Gold,2020-01-01,NaN
1,102,Jane,Smith,jane.smith@mail.com,9876543210,456 Oak St,Platinum,2019-06-15,NaN
2,103,Alice,Johnson,alice.j@mail.com,5551234567,321 Maple St,Silver,2021-03-10,NaN
3,104,Bob,Brown,bob.b@newmail.com,4449876543,654 Pine St,Silver,2018-11-25,NaN
4,105,Carol,White,carol.w@mail.com,3335558888,987 Cedar St,Gold,2022-07-01,NaN